// import "dart:convert";
// import "dart:io";
//
// import 'package:recase/recase.dart';
//
// void main(List<String> args) {
//   File fontsConfigFile = File(args[0]);
//
//   if (!fontsConfigFile.existsSync()) {
//     print('config file not found');
//     exit(0);
//   }
//
//   String content = fontsConfigFile.readAsStringSync();
//   List<dynamic> icons = json.decode(content);
//
//   List<String> generatedOutput = [
//     "library feather_icons;\n",
//     "import \"package:flutter/widgets.dart\";\n",
//     "import \"src/icon_data.dart\";\n\n",
//     "// THIS FILE IS AUTOMATICALLY GENERATED!\n\n",
//     "const Map<String, IconData> FeatherIconsMap = {\n"
//   ];
//
//   for (Map<String, dynamic> icon in icons) {
//     icon.forEach((String iconName, dynamic iconUnicode) =>
//         generatedOutput.add("'$iconName' : const FeatherIconData(0x$iconUnicode),\n"));
//   }
//
//   generatedOutput.add("};\n");
//
//   generatedOutput.add("class FeatherIcons {\n");
//
//   for (Map<String, dynamic> icon in icons) {
//     icon.forEach((String iconName, dynamic iconUnicode) =>
//         generatedOutput.add("static const IconData ${iconName.camelCase} = const FeatherIconData(0x$iconUnicode);\n"));
//   }
//
//   generatedOutput.add("}\n");
//
//   generatedOutput.add("class FeatherIconsSnakeCase {\n");
//
//   for (Map<String, dynamic> icon in icons) {
//     icon.forEach((String iconName, dynamic iconUnicode) =>
//         generatedOutput.add("static const IconData ${iconName.snakeCase} = const FeatherIconData(0x$iconUnicode);\n"));
//   }
//
//   generatedOutput.add("}\n");
//
//   File output = File('./lib/feather_icons.dart');
//   output.writeAsStringSync(generatedOutput.join());
// }
